name: build

# on events
on:
  release:
    types:
      - created

jobs:

  release-linux-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
    
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: amd64